; generated by ARM C/C++ Compiler, RVCT4.0 [Build 400]
; commandline armcc [-S main.c]
        ARM
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

main PROC
        PUSH     {r4,lr}
        ADR      r0,|L1.28|
        BL       __2printf
        ADR      r0,|L1.48|
        BL       __2printf
        MOV      r0,#0
        POP      {r4,pc}
        ENDP

|L1.28|
        DCB      "Welc"
        DCB      "ome "
        DCB      "to B"
        DCB      "AUM!"
        DCB      "\n\0\0\0"
|L1.48|
        DCB      "Happ"
        DCB      "y En"
        DCB      "gine"
        DCB      "erin"
        DCB      "g wi"
        DCB      "th u"
        DCB      "s!\n\0"

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

__ARM_use_no_argv EQU 0

        EXPORT __ARM_use_no_argv
        EXPORT main [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT __2printf [CODE]

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {FALSE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
