/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swt_dnd_about_Twoblock */

#ifndef _Included_swt_dnd_about_Twoblock
#define _Included_swt_dnd_about_Twoblock
#ifdef __cplusplus
extern "C++" {
#endif
/*
 * Class:     swt_dnd_about_Twoblock
 * Method:    add
 * Signature: (Lswt_dnd/User;)I
 */
JNIEXPORT jint JNICALL _Java_swt_1dnd_about_1Twoblock_add
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
