/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_twoblock_blockdesigner_modulewizard_CW_Wizard.h"
#include "BlockDesigner.h"
/* Header for class com_twoblock_blockdesigner_modulewizard_CW_Wizard */

JNIEXPORT jstring JNICALL Java_com_twoblock_blockdesigner_modulewizard_CW_1Wizard_ComponentCreate
(JNIEnv *env, jobject thisObj, jstring inJNIStr)
{
	const char *inCStr = env->GetStringUTFChars(inJNIStr, NULL); // Convert the JNI String (jstring) into C-String (char*)
	if (NULL == inCStr)
		return NULL;

	BDWriter writer;
	writer.writeModuleCode(inCStr);
	printf("ononononon");

	env->ReleaseStringUTFChars(inJNIStr, inCStr);
	return 0;
}
