/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
/* Header for class com_twoblock_blockdesigner_modulewizard_CW_Wizard */

#ifndef _Included_com_twoblock_blockdesigner_modulewizard_CW_Wizard
#define _Included_com_twoblock_blockdesigner_modulewizard_CW_Wizard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twoblock_blockdesigner_modulewizard_CW_Wizard
 * Method:    ComponentCreate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_twoblock_blockdesigner_modulewizard_CW_1Wizard_ComponentCreate
//  (JNIEnv *, jobject, jstring);
(JNIEnv *env, jobject thisObj, jstring inJNIStr);

#ifdef __cplusplus
}
#endif
#endif
