/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twoblock_blockdesigner_command_Handler_Command */

#ifndef _Included_com_twoblock_blockdesigner_command_Handler_Command
#define _Included_com_twoblock_blockdesigner_command_Handler_Command
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_twoblock_blockdesigner_command_Handler_Command
 * Method:    PushCommand
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twoblock_blockdesigner_command_Handler_1Command_PushCommand
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
