/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jdk_h/jni.h"
#include "../jdk_h/jni_md.h"
#include <string.h>
#include <stdlib.h>
//#include "../../BlockDesigner_Core/systemc-2.3.1_BD/src/BD_core/SimulationHandler/CommandQueue.h"	
#include "../../BlockDesigner_Core/systemc-2.3.1_BD/src/BD_core/SimulationHandler/SimulationHandler.h"	
/* Header for class com_twoblock_blockdesigner_command_Handler_Command */

using namespace BDapi;

#ifndef _Included_com_twoblock_blockdesigner_command_Handler_Command
#define _Included_com_twoblock_blockdesigner_command_Handler_Command
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_twoblock_blockdesigner_command_Handler_Command
 * Method:    PushCommand
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twoblock_blockdesigner_command_Handler_1Command_PushCommand
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
