/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../jdk_h/jni.h"
#include "../../BlockDesigner_Core/systemc-2.3.1_BD/src/BD_core/gui/StartSimulationThreads.h"	

using namespace BDapi;

/* Header for class com_twoblock_blockdesigner_command_Handler_SimulationInitThread */

#ifndef _Included_com_twoblock_blockdesigner_command_Handler_SimulationInitThread
#define _Included_com_twoblock_blockdesigner_command_Handler_SimulationInitThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twoblock_blockdesigner_command_Handler_SimulationInitThread
 * Method:    StartSimulationThreads
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twoblock_blockdesigner_command_Handler_1SimulationInitThread_StartSimulationThreads
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
