/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../BlockDesigner_Core/systemc-2.3.1_BD/src/BD_core/SimulationAPI/BDSim.h"	
/* Header for class com_twoblock_blockdesigner_command_Hanlder_CallBack */

#ifndef _Included_com_twoblock_blockdesigner_command_Hanlder_CallBack
#define _Included_com_twoblock_blockdesigner_command_Hanlder_CallBack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twoblock_blockdesigner_command_Hanlder_CallBack
 * Method:    CycleListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twoblock_blockdesigner_command_Hanlder_1CallBack_CycleListener
  (JNIEnv *, jobject);

/*
 * Class:     com_twoblock_blockdesigner_command_Hanlder_CallBack
 * Method:    StatusListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twoblock_blockdesigner_command_Hanlder_1CallBack_StatusListener
  (JNIEnv *, jobject);

/*
 * Class:     com_twoblock_blockdesigner_command_Hanlder_CallBack
 * Method:    OutputListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twoblock_blockdesigner_command_Hanlder_1CallBack_OutputListener
  (JNIEnv *, jobject);

/*
 * Class:     com_twoblock_blockdesigner_command_Hanlder_CallBack
 * Method:    ModuleInfoListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twoblock_blockdesigner_command_Hanlder_1CallBack_ModuleInfoListener
  (JNIEnv *, jobject);

/*
 * Class:     com_twoblock_blockdesigner_command_Hanlder_CallBack
 * Method:    ErrorListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twoblock_blockdesigner_command_Hanlder_1CallBack_ErrorListener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
